### ISSUE TITLE
Explore Alternative Syntaxes

### ISSUE THREAD

**Issue by grassator** [grassator/pama#1]
While current syntax is somewhat IDE-friendly, but feels a bit clunky. It also has a limitation of only matching one element and disallows complex expressions. Below are a couple of alternatives.

### Template Literals

```js
when(1, 'foo') `
  is (Number, _) then ${() => {}}
  else ${'😀'}
`;
```
#### Benefits
- JIT compilation is possible and the whole matching should be very fast on repeated calls
- it is possible to have any syntax, which is nice for `_`, `...` (splats) and capturing of values.

#### Drawbacks
- It's a DSL, so people need to learn new syntax
- Editors and IDEs have no support for this
- There is no static validation (can be mitigated with an eslint plugin)

### Conditional Expressions

```js
 when(value, ({ matches, _ }) =>
    value === 5 ? () => {} :
    matches({foo: _}) ? () => {} :
    undefined
);
```
#### Benefits
- Mostly JS syntax with a little sugar in auto-bound helper functions, like `matches`
- Full support from IDEs
- Required "otherwise" branch

#### Drawbacks
- Capturing of values are still awkward
- Required "otherwise" branch (yes, it is also a benefit)

**Comment by mo-gr** [comment]
The combination of "It's a DSL, so people need to learn new syntax" and "Editors and IDEs have no support for this" is a deal breaker for me. I would put `Template Literals` off the table.

`Conditional Expressions` have some beauty and elegance to them

**Comment by grassator** [comment]
@mo-gr decided on a mixture between current style with global matchers and the conditionals. I think it turned out pretty well — small and quite powerful.
